language: generic


sudo: required
services: docker
dist: bionic

install:
  - sudo apt-get install python3-docutils
  - source texlive.sh


cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive


script: 
  - l3build ctan -H || ( cat build/*/`ls -t  build/*/*.log | head -n1 | xargs basename | cut -f 1 -d . `.log && false )

deploy:
  provider: releases
  api_key:
    secure: kUK8NofPipXrARSWVpFQN6eUdiIxSqgUQJr/wQVO+q1DTtT2W5ztjAZ/jU30IETInvcCt8Wo/3BtilPFtOiYDGvwV6uZBJbAaQh/zhjAr98w/4JafjsCHUHJfZ+cxn9NlhqZQXtR3mu6xVZt2DF5enMcedN367/0XXzdGOn/yXx0U0Ceeqs5/d0pPhNJ0ACp+N2whQhSyDOz2iYB7cba9lxP8FHjWLZlwgBMFh6oCIyVXdt9+9gCi0j63ygy1iwe7ewblISGHYtnYhQ1pUF8/PLqEylc8nYuXfd0red4gY/p30wb0fGpX9WwBErL2XBflDjH8WAxHUyatJcDBd+F1DfB8EwKl4rghdtDcuUKMdiJfXn8MyvYIPLgkMK9vUr/Pq2drqCbMa2Qc8mmamBUbMPeD2ZdzYnfIwDHswqS9z2ENUeqDf9xUmzEoybfnKXNiJf9LglMnRp+e8+BQkWtkaG+/rpigKXK7Xvw/20xq0SEz+9i1MTNepfJrALnpSKBZAkKnDGdoMTCfmni+k0LnThbxEUQikaHjcoSe7UgQtEnhgGFcPRRiIY2WX+XTEbStSfZq3mNt68vdO0cyYOTNYTB/KNHx5tmuIxF/Y3cHzqW/xrNabPwbpP50oQPmoJ3+1015GD5mU2mZzk6Ev54xIvjhajQwEIYioFL7snXYJA=
  file: luaotfload-dev.zip
  skip_cleanup: true
  on:
    tags: true
  prerelease: true
  draft: true
