name: Automated testing
on:
  push:

jobs:
  l3build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.texlive
            /tmp/texlive
          key: texlive-v0-${{ steps.get-id.outputs.id }}
          restore-keys: texlive-v0-
      - name: Install TeX Live
        uses: pgf-tikz/actions/install-tl@54ab9db16b5a993502431b719e5bd8fc341482e6
        with:
          packages:
            # Needed for any use of texlua even if not testing LuaTeX
            l3build latex latex-bin luatex latex-bin-dev
            #
            # Required to build plain and LaTeX formats:
            # TeX90 plain for unpacking, pdfLaTeX, LuaLaTeX and XeTeX for tests
            cm etex knuth-lib tex tex-ini-files unicode-data
            #
            # various tools / dependencies of other packages
            ctablestack filehook ifoddpage iftex luatexbase trimspaces
            oberdiek etoolbox xkeyval ucharcat xstring everyhook
            svn-prov setspace csquotes everysel
            #
            # slices from oberdiek
            atbegshi atveryend bigintcalc bitset bookmark epstopdf-pkg etexcmds
            gettitlestring hologo hycolor intcalc kvdefinekeys kvsetkeys
            letltxmacro ltxcmds luacolor pdfescape pdflscape pdftexcmds refcount
            rerunfilecheck uniquecounter
            #
            # graphics
            graphics xcolor graphics-def pgf
            #
            # fonts support - perhaps take here luaotfload out of the list ...
            # or is it installed as dependency anyway?
            fontspec microtype unicode-math luaotfload ttfutils
            #
            # fonts
            sourcecodepro asana-math ebgaramond tex-gyre amsfonts gnu-freefont
            opensans fira tex-gyre-math junicode lm lm-math amiri ipaex xits
            libertine coelacanth fontawesome stix2-otf dejavu
            luatexko unfonts-core cjk-ko iwona libertinus-fonts fandol
            cm-unicode noto cuprum
            #
            # languages
            luatexja arabluatex babel babel-english
            #
            # math
            amsmath lualatex-math latex-amsmath-dev
            #
            # a few more packages
            luacode environ adjustbox collectbox ms varwidth geometry url ulem lua-ul
            #
            # some packages for the documentation
            caption fancyvrb hyperref inconsolata listings luatex85 mdwtools
            metalogo pdfpages pgf-blur standalone tikzducks tikzlings titlesec
            tocloft tools
            #
            # Assuming a 'basic' font set up, metafont is required to avoid
            # warnings with some packages and errors with others
            metafont mfware texlive-scripts
      - name: Install docutils
        run: sudo apt-get install python3-docutils
      - name: Run l3build
        run: l3build install && l3build ctan -H --show-log-on-error
      - name: Archive CTAN packages
        uses: actions/upload-artifact@v2
        with:
          name: CTAN
          path: build/distrib/ctan/*.zip
      - name: Archive test output
        uses: actions/upload-artifact@v2
        with:
          name: testfiles
          path: build/test*
          retention-days: 1
